version: "3.9"

services:
  boostseo-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: boostseo-backend
    restart: unless-stopped
    expose:
      - "8000"

  boostseo-frontend:
    build:
      context: ./frontend
    container_name: boostseo-frontend
    restart: unless-stopped
    ports:
      - "3012:80"
    depends_on:
      - boostseo-backend
